name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run root tests
        run: make test

      - name: Generate Templ files
        run: make app-generate

      - name: Run bootstrap tests
        run: make app-test

      - name: Build bootstrap application
        run: make app-build
