name: "Validations"
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  Static-Analysis:
    name: "Static analysis"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0

    - name: Bootstrap environment
      uses: ./.github/actions/bootstrap

    - name: Run static analysis
      run: make static-analysis

  Unit-Test:
    name: "Unit tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Run static-analysis tests
        run: make static-analysis

      - uses: actions/upload-artifact@v4
        run: make test 